### ISSUE TITLE
Fatal Error in running the script

### ISSUE THREAD

**Issue by bumbum69420** [adityajoshicreed/CS-Omegle-Bot#2]
Hi there! I hope it isn't too late to get a response for this... However I tried running the file and got to where it prompted as to whether or not I wanted to use a proxy and this came up after responding with "n"

`Traceback (most recent call last):
  File "CS.Omegle.Bot.py", line 106, in <module>
    display = Display(visible=1, size=(800, 600))
  File "C:\Python27\lib\site-packages\pyvirtualdisplay\display.py", line 34, in __init__
    self._obj = self.display_class(
  File "C:\Python27\lib\site-packages\pyvirtualdisplay\display.py", line 53, in display_class
    cls.check_installed()
  File "C:\Python27\lib\site-packages\pyvirtualdisplay\xephyr.py", line 30, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "C:\Python27\lib\site-packages\easyprocess\__init__.py", line 182, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xephyr', '-help']
OSError=[Error 2] The system cannot find the file specified
Program install error!`

**Comment by adityajoshicreed** [comment]
This software is outdated. I am thinking of making the new version by the end of this year.

**Comment by bumbum69420** [comment]
I got it to work on linux
